### ISSUE TITLE
Error running ApplyCypressFX2RegisterEnums

### ISSUE THREAD

**Issue by kilate** [gsuberland/ghidra-cypress-fx2#2]
Hi, 
getting this error when running the script. 

Thanks for sharing!

ApplyCypressFX2RegisterEnums.java> Running...
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_BREAKPT
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_CPUCS
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP1INCFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP1OUTCFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP2CFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP2FIFOCFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP2FIFOPFH
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP2ISOINPKTS
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP4CFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP4FIFOCFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP4FIFOPFH
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP4ISOINPKTS
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP6CFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP6FIFOCFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP6FIFOPFH
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP6ISOINPKTS
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP8CFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP8FIFOCFG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP8FIFOPFH
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_EP8ISOINPKTS
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_FIFOPINPOLAR
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_FIFORESET
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_IFCONFIG
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_INPKTEND
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_OUTPKTEND
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_PINFLAGSAB
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_PINFLAGSCD
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_REVCTL
ApplyCypressFX2RegisterEnums.java> FX2_REG_BITS_UART230
ApplyCypressFX2RegisterEnums.java> FX2_REG_VAL_GPIFHOLDTIME
ApplyCypressFX2RegisterEnums.java> Enum count: 30
> Error running script: ApplyCypressFX2RegisterEnums.java
java.lang.ClassCastException: class ghidra.program.database.data.EnumDB cannot be cast to class ghidra.program.model.data.EnumDataType (ghidra.program.database.data.EnumDB and ghidra.program.model.data.EnumDataType are in unnamed module of loader ghidra.GhidraClassLoader @22a71081)
	at ApplyCypressFX2RegisterEnums.run(ApplyCypressFX2RegisterEnums.java:62)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:395)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:250)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:228)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kilate** [comment]
BTW,
---------------------------------------------------
Build Date: 2022-Nov-01 1334 EDT
Ghidra Version: 10.2
Java Home: /opt/jdk-17.0.5
JVM Version: Oracle Corporation 17.0.5
OS: Linux 5.15.0-53-generic amd64
